name: Publish
on:
  release:
    types: published

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'liberica'
          cache: 'gradle'

      - name: Publish to Central Repository
        uses: ihub-pub/bot/publish@a2f4e260e3449ecdbf2948a4e4ad47a2d5b626b0 # v3.0.2
        with:
          repoUsername: ${{ secrets.HENRY_REPO_USERNAME }}
          repoPassword: ${{ secrets.HENRY_REPO_PASSWORD }}
          release: true
          parallel: true
          applyGithubPom: false
          signingKeyId: ${{ secrets.PUBLIC_SIGNING_KEY_ID }}
          signingPassword: ${{ secrets.PUBLIC_SIGNING_PASSWORD }}
          signingSecretKey: ${{ secrets.PUBLIC_SIGNING_SECRET_KEY }}
