name: Publish
on:
  release:
    types: published

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'liberica'
          cache: 'gradle'

      - name: Publish to Central Repository
        uses: ihub-pub/bot/publish@a2f4e260e3449ecdbf2948a4e4ad47a2d5b626b0 # v3.0.2
        with:
          repoUsername: ${{ secrets.HENRY_REPO_USERNAME }}
          repoPassword: ${{ secrets.HENRY_REPO_PASSWORD }}
          release: true
          parallel: true
          applyGithubPom: false
          signingKeyId: ${{ secrets.PUBLIC_SIGNING_KEY_ID }}
          signingPassword: ${{ secrets.PUBLIC_SIGNING_PASSWORD }}
          signingSecretKey: ${{ secrets.PUBLIC_SIGNING_SECRET_KEY }}
